- name: Install LDAP packages
  apt: pkg={{item}} state=installed
  with_items:
    - slapd
    - ldap-utils
  tags:
    - ldap

- name: Install custom LDAP schemas
  copy: src={{ item }} dest=/etc/ldap/schema/ owner=root group=root mode=0644
  with_fileglob:
    - etc/ldap/schema/*
  tags:
    - ldap

- name: Install slapd Debian default file
  template: src=slapd_default.j2 dest=/etc/default/slapd owner=root group=root mode=0644
  notify:
    - restart slapd
  tags:
    - ldap

- name: Check whether the mail schema exists
  command: ldapsearch -LLL -Y EXTERNAL -H ldapi:/// -b cn=schema,cn=config '(&(cn={*}mail)(objectClass=olcSchemaConfig))'
  register: ldapsearch_mail_schema
  tags:
    - ldap

- name: Add mail schema
  command: ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/ldap/schema/mail.schema.ldif
  when: ldapsearch_mail_schema.stdout == ""
  tags:
    - ldap

- name: Generate hash of LDAP admin password
  command: slappasswd -s {{ldap_admin_pass}}
  register: slappasswd_out
  tags:
    - ldap

- name: Save fact with hashed LDAP password
  set_fact: hashed_ldap_password={{slappasswd_out.stdout}}
  tags:
    - ldap

- name: Create LDAP entries for all managed domains...
  include: ldap-domain-tree.yml
  with_items: {{ldap_managed_domains}}
