- name: Add Webmin APT key
  apt_key: url=http://www.webmin.com/jcameron-key.asc state=present
  tags:
    - usermin

- name: Add Webmin APT repository
  apt_repository: repo='deb http://download.webmin.com/download/repository sarge contrib' state=present update_cache=yes
  tags:
    - usermin

- name: Install Usermin
  apt: pkg=usermin state=installed
  tags:
    - usermin

- name: Install Usermin's miniserv.conf
  copy: src=etc/usermin/miniserv.conf dest=/etc/usermin/miniserv.conf owner=root group=root mode=0644
  notify:
    - restart usermin
  tags:
    - usermin
