
- name: Install MySQL and dependencies
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - python-mysqldb
    - python-configparser
    - mysql-common
    - mysql-client
    - mysql-server
    - php5-mysqlnd
  notify:
    - restart mysql
  tags:
    - mysql

- name: Set MySQL root password
  debconf: name=mysql-server-5.5 question="{{item}}" vtype=password value="{{mysql_root_password}}"
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again
  tags:
    - mysql

- name: Reconfigure MySQL
  command: dpkg-reconfigure -f noninteractive mysql-server-5.5
  tags:
    - mysql
