---

- name: restart ssh
  service: name=ssh state=restarted

- name: rebuild rkhunter proplist
  command: rkhunter --propupd

- name: disable network offloading
  command: /opt/disable-network-offload.sh

- name: update mail aliases
  command: newaliases
