- name: Install packages necessary for backup system
  apt: pkg={{item}} state=installed
  with_items:
    - backupninja
    - duplicity
    - gnupg
    - rdiff-backup
  tags:
    - base
    - backup

- name: Install backupninja.conf
  copy: src=etc/backupninja.conf dest=/etc/backupninja.conf group=root owner=root mode=0644
  tags:
    - base
    - backup
