- name: Create suricata user
  user: name=suricata shell=/bin/false createhome=no
  tags: base

- name: Create suricata directories
  file: name={{item}} state=directory owner=suricata group=suricata mode=0700
  with_items:
    - /var/log/suricata
    - /var/run/suricata
  tags: base

- name: Install Oinkmaster configuration
  copy: src=etc/oinkmaster.conf dest=/etc/oinkmaster.conf owner=root group=root mode=0644
  tags: base

- name: Install Suricata configuration file
  copy: src=etc/suricata/suricata.yaml dest=/etc/suricata/suricata.yaml owner=root group=root mode=0644
  notify:
    - restart suricata
  tags: base

- name: Install Suricata Debian default file
  copy: src=etc/default/suricata dest=/etc/default/suricata owner=root group=root mode=0644
  notify:
    - restart suricata
  tags: base

- name: Install Suricata custom rules file
  copy: src=etc/snort/rules/local.rules dest=/etc/snort/rules/local.rules owner=root group=root mode=0644
  notify:
    - restart suricata
  tags: base

- name: Install Oinkmaster cron job
  copy: src=etc/cron.daily/oinkmaster dest=/etc/cron.daily/oinkmaster owner=root group=root mode=0755
  tags: base

- name: Make sure Suricata is enabled
  service: name=suricata enabled=yes
  tags: base
