- name: Set options for slapd package (password, domain name)
  debconf: name=slapd question={{ item.q }} vtype={{ item.t }} value={{ item.v }}
  with_items:
    - { q: 'slapd/password1', t: 'password', v: "{{ ldap_admin_pass }}" }
    - { q: 'slapd/password2', t: 'password', v: "{{ ldap_admin_pass }}" }
    - { q: 'slapd/domain', t: 'string', v: "{{ domain_name }}" }
  tags:
    - ldap

- name: Install LDAP packages
  apt: pkg={{item}} state=installed
  with_items:
    - slapd
    - ldap-utils
  tags:
    - ldap

- name: Install custom LDAP schemas
  copy: src={{ item }} dest=/etc/ldap/schema/ owner=root group=root mode=0644
  with_fileglob:
    - etc/ldap/schema/*
  notify:
    - restart slapd
  tags:
    - ldap

- name: Install LDAP configuration (slapd.conf)
  template: src=slapd.conf.j2 dest=/etc/ldap/slapd.conf owner=root group=root mode=0644
  notify:
    - restart slapd
  tags:
    - ldap

- name: Install slapd Debian default file
  copy: src=etc/default/slapd dest=/etc/default/slapd owner=root group=root mode=0644
  notify:
    - restart slapd
  tags:
    - ldap
