- name: Install LDAP packages
  apt: pkg={{item}} state=installed
  with_items:
    - slapd
  tags:
    - ldap

- name: Install custom LDAP schemas
  copy: src={{ item }} dest=/etc/ldap/schema/ owner=root group=root mode=0644
  with_fileglob:
    - etc/ldap/schema/*
  notify:
    - restart slapd
  tags:
    - ldap

- name: Install LDAP configuration (slapd.conf)
  template: src=slapd.conf.j2 dest=/etc/ldap/slapd.conf owner=root group=root mode=0644
  notify:
    - restart slapd
  tags:
    - ldap

- name: Install slapd Debian default file
  copy: src=etc/default/slapd dest=/etc/default/slapd owner=root group=root mode=0644
  notify:
    - restart slapd
  tags:
    - ldap
