- name: Insert umask profile file
  copy: src=etc/profile.d/umask_set.sh dest=/etc/profile.d/ansible_umask_set.sh owner=root group=root
  tags: base

- name: Install General System Security packages
  apt: pkg={{item}} state=installed
  with_items:
    - apticron
    - openssh-server
    - postfix
    - ufw
    - bash
  tags: base

- name: Install SSHd configuration
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config group=root owner=root
  notify:
    - restart ssh
  tags: base

- name: Install UFW files
  copy: src={{item}} dest=/{{item}} group=root owner=root
  with_items:
    - etc/default/ufw
    - etc/ufw/ufw.conf
    - etc/ufw/before.rules
  tags: firewall

- name: Enable UFW
  ufw: state=enabled logging=on policy=deny
  tags: firewall

- name: Open ports in UFW (inbound)
  ufw: rule=allow port={{item}} direction=in
  with_items:
    - 22
    - 1194
  tags: firewall

- name: Open ports in UFW (outbound)
  ufw: rule=allow port={{item}} direction=out
  with_items:
    - 53
    - 80
    - 443
  tags: firewall

- name: Install Apticron configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf group=root owner=root mode=0644
  tags: base

- include: unwanted-pkgs.yml
- include: sysctl.yml
- include: vpn.yml
