- name: Insert umask profile file
  copy: src=umask_set.sh dest=/etc/profile.d/ansible_umask_set.sh owner=root group=root

- name: Install General System Security packages
  apt: pkg={{item}} state=installed
  with_items:
    - apticron
    - openssh-server
    - postfix
    - ufw

- name: Install SSHd configuration
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config group=root owner=root
  notify:
    - restart ssh

- name: Install Apticron configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf group=root owner=root mode=0644

- include: unwanted-pkgs.yml
- include: sysctl.yml
