- name: Insert umask profile file
  copy: src=etc/profile.d/umask_set.sh dest=/etc/profile.d/ansible_umask_set.sh owner=root group=root

- name: Install General System Security packages
  apt: pkg={{item}} state=installed
  with_items:
    - apticron
    - openssh-server
    - postfix
    - ufw

- name: Install SSHd configuration
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config group=root owner=root
  notify:
    - restart ssh

- name: Install UFW configuration
  copy: src=etc/default/ufw dest=/etc/default/ufw group=root owner=root
  copy: src=etc/ufw/ufw.conf dest=/etc/ufw/ufw.conf group=root owner=root

- name: Enable UFW
  ufw: state=enabled logging=on policy=deny

- name: Open ports in UFW (inbound)
  ufw: rule=allow port={{item}} direction=in
  with_items:
    - 22

- name: Open ports in UFW (outbound)
  ufw: rule=allow port={{item}} direction=out
  with_items:
    - 53
    - 80
    - 443

- name: Install Apticron configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf group=root owner=root mode=0644

- include: unwanted-pkgs.yml
- include: sysctl.yml
