- name: Install login.defs
  copy: src=etc/login.defs dest=/etc/login.defs owner=root group=root mode=0644
  tags: base

- name: Install PAM common-session file with umask module enabled
  copy:
  args:
    src: etc/pam.d/{{ ansible_distribution_release }}-common-session
    dest: /etc/pam.d/common-session
    owner: root
    group: root
    mode: 0644
  tags: base

- name: Add backports Debian repository
  apt_repository:
  args:
    repo: 'deb http://http.debian.net/debian {{ ansible_distribution_release }}-backports main'
    state: present
    update_cache: yes
  tags: base

- name: Install General System Security packages
  apt: pkg={{item}} state=installed
  with_items:
    - apticron
    - cron
    - openssh-server
    - postfix
    - ufw
    - bash
    - chkrootkit
    - wget
    - unhide
    - libpam-umask
    - ethtool
    - debconf-utils
  tags:
    - base
    - firewall

- name: Install SSHd configuration
  template:
  args:
    src: "{{ ansible_distribution_release }}-sshd_config.j2"
    dest: /etc/ssh/sshd_config
    group: root
    owner: root
  notify:
    - restart ssh
  tags: base

- name: Install UFW files
  copy: src={{item}} dest=/{{item}} group=root owner=root
  register: ufw_config_files
  with_items:
    - etc/default/ufw
    - etc/ufw/ufw.conf
    - etc/ufw/before.rules
  tags: firewall

- name: Disable UFW
  ufw: state=disabled
  when: ( ufw_config_files|changed )
  tags: firewall

- name: Reload UFW
  ufw: state=reloaded
  when: ( ufw_config_files|changed )
  tags: firewall

- name: Open ports in UFW (inbound)
  ufw: rule=allow port={{item}} direction=in
  with_items:
    - 22
    - 25
  tags: firewall

- name: Open ports in UFW (outbound)
  ufw: rule=allow port={{item}} direction=out
  with_items:
    - 53
    - 25
    - 80
    - 443
  tags: firewall

- name: Enable UFW
  ufw: state=enabled logging=on policy=deny
  tags: firewall

- name: Install Apticron configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf group=root owner=root mode=0644
  tags: base

- name: Install chkrootkit configuration
  copy: src=etc/chkrootkit.conf dest=/etc/chkrootkit.conf group=root owner=root mode=0600
  tags: base

- name: Install chkrootkit daily cron job script
  copy: src=etc/cron.daily/chkrootkit dest=/etc/cron.daily/chkrootkit group=root owner=root mode=0755
  tags: base

- name: Install /etc/aliases
  template: src=aliases.j2 dest=/etc/aliases group=root owner=root mode=0644
  notify:
    - update mail aliases
  tags: base

- include: unwanted-pkgs.yml
- include: sysctl.yml
