- name: Install login.defs
  copy: src=etc/login.defs dest=/etc/login.defs owner=root group=root mode=0644
  tags: base

- name: Install PAM common-session file with umask module enabled
  copy: src=etc/pam.d/common-session dest=/etc/pam.d/common-session owner=root group=root mode=0644
  tags: base

- name: Add backports Debian repository
  copy: src=etc/apt/sources.list.d/backports.list dest=/etc/apt/sources.list.d/backports.list owner=root group=root mode=0644
  notify:
    - update apt database
  tags: base

- name: Update APT database
  apt: update_cache=yes
  tags: base

- name: Install General System Security packages
  apt: pkg={{item}} state=installed
  with_items:
    - apticron
    - cron
    - openssh-server
    - postfix
    - ufw
    - bash
    - chkrootkit
    - wget
    - unhide
    - rkhunter
    - libpam-umask
    - ethtool
    - debconf-utils
  tags: base

- name: Install backports packages
  apt: pkg={{item}} default_release=wheezy-backports state=installed
  with_items:
    - suricata
    - oinkmaster
  tags: base

- name: Install SSHd configuration
  template: src=sshd_config.j2 dest=/etc/ssh/sshd_config group=root owner=root
  notify:
    - restart ssh
  tags: base

- name: Install UFW files
  copy: src={{item}} dest=/{{item}} group=root owner=root
  with_items:
    - etc/default/ufw
    - etc/ufw/ufw.conf
    - etc/ufw/before.rules
  tags: firewall

- name: Enable UFW
  ufw: state=enabled logging=on policy=deny
  tags: firewall

- name: Open ports in UFW (inbound)
  ufw: rule=allow port={{item}} direction=in
  with_items:
    - 22
    - 25
    - 1194
  tags: firewall

- name: Open ports in UFW (outbound)
  ufw: rule=allow port={{item}} direction=out
  with_items:
    - 53
    - 25
    - 80
    - 443
  tags: firewall

- name: Install Apticron configuration
  template: src=apticron.conf.j2 dest=/etc/apticron/apticron.conf group=root owner=root mode=0644
  tags: base

- name: Install chkrootkit configuration
  copy: src=etc/chkrootkit.conf dest=/etc/chkrootkit.conf group=root owner=root mode=0600
  tags: base

- name: Install chkrootkit warning suppression pattern file
  template: src=chkrootkit.ignore.j2 dest=/etc/chkrootkit.ignore group=root owner=root mode=0644
  tags: base

- name: Install chkroot daily cron job script
  copy: src=etc/cron.daily/chkrootkit dest=/etc/cron.daily/chkrootkit group=root owner=root mode=0755
  tags: base

- name: Install rkhunter Debian default file
  copy: src=etc/default/rkhunter dest=/etc/default/rkhunter group=root owner=root mode=0644
  tags: base

- name: Install rkhunter configuration
  copy: src=etc/rkhunter.conf dest=/etc/rkhunter.conf group=root owner=root mode=0600
  notify:
    - rebuild rkhunter proplist
  tags: base

- name: Create /etc/initramfs/post-update.d
  file: path=/etc/initramfs/post-update.d state=directory owner=root group=root mode=0755
  tags: base

- name: Add rkhunter initramfs post-update script
  copy: src=etc/initramfs/post-update.d/rkhunter dest=/etc/initramfs/post-update.d/rkhunter owner=root group=root mode=0755
  tags: base

- name: Install rkhunter boot-job
  copy: src=etc/cron.d/rkhunter-boot dest=/etc/cron.d/rkhunter-boot group=root owner=root mode=0644
  tags: base

- name: Install /etc/aliases
  template: src=aliases.j2 dest=/etc/aliases group=root owner=root mode=0644
  notify:
    - update mail aliases
  tags: base

- name: Set /etc/mailname with our FQDN
  copy: dest=/etc/mailname content="{{ server_name }}.{{ domain_name }}" group=root owner=root mode=0644
  notify:
    - restart postfix
  tags: base

- include: unwanted-pkgs.yml
- include: sysctl.yml
- include: tls.yml
- include: vpn.yml
- include: ids.yml
- include: backup.yml
- include: ldap.yml
- include: virtualmail.yml
