- name: Install General System Security packages
  apt: pkg={{item}} state=installed
  with_items:
    - apticron
    - openssh-server

- name: Install SSHd configuration
  copy: src=sshd_config dest=/etc/ssh/sshd_config group=root owner=root
  notify:
    - restart ssh

- include: unwanted-pkgs.yml
