- name: Add OpenSUSE PGP signing key
  apt_key: url=http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/Release.key state=present
  tags:
    - owncloud

- name: Add OpenSUSE repository for Owncloud package
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /' state=present update_cache=yes
  tags:
    - owncloud
