- name: Add OpenSUSE PGP signing key
  apt_key: url=http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/Release.key state=present
  tags:
    - owncloud

- name: Add OpenSUSE repository for Owncloud package
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /' state=present update_cache=yes
  tags:
    - owncloud

- name: Install Owncloud and dependencies
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - mysql-common
    - mysql-client
    - mysql-server
    - php5-mysqlnd
    - php-apc
    - owncloud-server
  notify:
    - restart php5-fpm
  tags:
    - owncloud

- name: Set MySQL root password
  debconf: name=mysql-server-5.5 question={{ item }} vtype=password value={{ mysql_root_password }}
  with_items:
    - mysql-server/root_password
    - mysql-server/root_password_again
  tags:
    - owncloud

- name: Reconfigure MySQL
  command: dpkg-reconfigure -f noninteractive mysql-server-5.5
  tags:
    - owncloud

- name: Setting correct permissions in Owncloud directory
  file: path=/var/www/owncloud/{{item.dirname}} group=www owner=www recurse={{item.rec}}
  with_items:
    - { dirname: apps, rec: no }
    - { dirname: config, rec: yes }
    - { dirname: data, rec: no }
  tags:
    - owncloud
