- name: Install Samba packages (from backports)
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - samba
    - smbldap-tools
  tags:
    - samba

- name: Install samba configuration
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=0644
  notify:
    - restart samba
  tags:
    - samba

- name: Check existence of Samba LDAP schema file (/etc/ldap/schema/samba.schema)
  stat: path=/etc/ldap/schema/samba.schema
  register: samba_schema
  tags:
    - samba

- name: Copy compressed Samba LDAP schema file from Samba installation
  command: cp /usr/share/doc/samba/examples/LDAP/samba.schema.gz /etc/ldap/schema/
  when: ( samba_schema.stat.exists == false )
  tags:
    - samba

- name: Uncompress Samba LDAP schema file
  command: gunzip /etc/ldap/schema/samba.schema.gz
  when: ( samba_schema.stat.exists == false )
  tags:
    - samba

- name: Fix permissions on Samba LDAP schema
  file: path=/etc/ldap/schema/samba.schema owner=root group=root mode=0644
  tags:
    - samba

- name: Reference Samba schema from slapd configuration
  lineinfile: dest=/etc/ldap/slapd.conf state=present insertafter='^include' line='include      /etc/ldap/schema/samba.schema'
  notify:
    - restart slapd
  tags:
    - samba

- name: Check whether organizationalUnit users LDAP entry exists
  command: ldapsearch -x -b dc={{ domain_name|split('.')|join(',dc=') }} ou=users
  ignore_errors: true
  register: ldapsearch_users_ou
  tags:
    - samba

- name: Add organizationalUnit users LDAP entry (1/2)
  template: src=users_ou.ldif.j2 dest=/tmp/users_ou.ldif owner=root group=root mode=0644
  when: ldapsearch_users_ou.stdout.find('# numEntries') == -1
  tags:
    - samba

- name: Add organizationalUnit users LDAP entry (2/2)
  command: ldapadd -D cn=admin,dc={{ domain_name|split('.')|join(',dc=') }} -w {{ ldap_admin_pass }} -f /tmp/users_ou.ldif
  when: ldapsearch_users_ou.stdout.find('# numEntries') == -1
  tags:
    - samba

- name: Remove LDIF temporary file for organizationalUnit users entry
  file: path=/tmp/users_ou.ldif state=absent
  tags:
   - samba
