- name: Install Samba packages (from backports)
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - samba
    - smbldap-tools
  tags:
    - samba

- name: Install samba configuration
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=0644
  notify:
    - restart samba
  tags:
    - samba

- name: Check existence of Samba LDAP schema file
  stat: path=/etc/ldap/schema/samba.schema
  register: samba_schema
  tags:
    - samba

- name: Copy compressed Samba LDAP schema file from Samba installation
  command: cp /usr/share/doc/samba/examples/LDAP/samba.schema.gz /etc/ldap/schema/
  when: ( samba_schema.stat.exists == false )
  tags:
    - samba

- name: Uncompress Samba LDAP schema file
  command: gunzip /etc/ldap/schema/samba.schema.gz
  when: ( samba_schema.stat.exists == false )
  tags:
    - samba
