- name: Install Samba packages (from backports)
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - samba
  tags:
    - samba

- name: Install samba configuration
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode=0644
  notify:
    - restart samba
  tags:
    - samba
