- name: Make sure unwanted packages are absent
  apt: pkg={{item}} state=absent purge=yes
  with_items:
    - nfs-common
    - rpcbind
    - exim4
    - exim4-base
    - exim4-config
    - exim4-daemon-light
