- name: Install dovecot packages
  apt: pkg={{item}} state=installed
  with_items:
    - dovecot-core
    - dovecot-imapd
    - dovecot-pop3d
    - dovecot-ldap
    - postfix-ldap
  tags:
    - vmail

- name: Create virtual mail group
  group: name=vmail gid=5000 state=present
  tags:
    - vmail

- name: Create virtual mail user
  user: name=vmail uid=5000 home=/var/virtualmail createhome=no group=vmail shell=/bin/nologin
  tags:
    - vmail

- name: Create /var/virtualmail
  file: path=/var/virtualmail state=directory owner=vmail group=vmail mode=0755
  tags:
    - vmail

- name: Ensure correct ownership in /var/virtualmail
  file: path=/var/virtualmail state=directory owner=vmail group=vmail recurse=yes
  tags:
    - vmail

- name: Install postfix main configuration
  template: src=postfix-main.cf.j2 dest=/etc/postfix/main.cf owner=root group=root mode=0644
  notify:
    - restart postfix
  tags:
    - vmail

- name: Install postfix LDAP-related config files
  template: src={{ item }}.j2  dest=/etc/postfix/{{ item }} group=root owner=root mode=0644
  with_items:
    - ldap-accounts.cf
    - ldap-aliases.cf
  notify:
    - restart postfix
  tags:
    - vmail

- name: Install Dovecot main configuration
  template: src=dovecot.conf.j2 dest=/etc/dovecot/dovecot.conf group=root owner=root mode=0644
  notify:
    - restart dovecot
  tags:
    - vmail
- name: Install Dovecot LDAP configuration
  template: src=dovecot-ldap.conf.j2 dest=/etc/dovecot/dovecot-ldap.conf group=root owner=root mode=0644
  notify:
    - restart dovecot
  tags:
    - vmail
