- name: Install VPN-related packages
  apt: pkg={{item}} state=installed
  with_items:
    - openvpn
    - dnsmasq

- name: Install VPN server configuration files
  synchronize: src=etc/openvpn dest=/etc/openvpn checksum=yes
