- name: Install VPN-related packages
  apt: pkg={{item}} state=installed
  with_items:
    - openvpn
    - dnsmasq
  tags: vpn

- name: Install OpenVPN server configuration
  copy: src=etc/openvpn/server.conf dest=/etc/openvpn/server.conf owner=root group=root mode=0644
  notify:
    - restart openvpn
  tags: vpn

- name: Install OpenVPN scripts
  copy: src={{item}} dest=/etc/openvpn/ owner=root group=root mode=0755
  with_fileglob:
    - etc/openvpn/server-*.sh
  notify:
    - restart openvpn
  tags: vpn

- name: Install OpenVPN Debian default file
  copy: src=etc/default/openvpn dest=/etc/default/openvpn owner=root group=root mode=0644
  tags: vpn

- name: Allow VPN traffic by firewall
  ufw: rule=allow {{item}}=10.1.0.0/24
  with_items:
    - to
    - from
  tags: vpn

- name: Install dnsmasq configuration
  copy: src=etc/dnsmasq.d/vpn dest=/etc/dnsmasq.d/vpn group=root owner=root mode=0644
  notify:
    - restart dnsmasq
  tags: vpn
