- name: Install roundcube and dependencies (from backports)
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - php5-fpm
    - php5
    - php5-common
    - roundcube-sqlite3
    - roundcube-core
    - roundcube
  tags:
    - webmail

- name: Install php5-fpm configuration
  copy: src=etc/php5/fpm/{{item}} dest=/etc/php5/fpm/{{item}} owner=root group=root mode=0644
  with_items:
    - php-fpm.conf
    - pool.d/www.conf
  notify:
    - restart php5-fpm
  tags:
    - webmail

- name: Install php5-fpm nginx configuration
  copy: src=etc/nginx/conf.d/php5-fpm.conf dest=/etc/nginx/conf.d/php5-fpm.conf owner=root group=root mode=0644
  notify:
    - restart nginx
  tags:
    - webmail
