- name: Configure roundcube debconf parameters
  debconf: name=roundcube-core question={{ item.q }} vtype={{ item.t }} value={{ item.v }}
  with_items:
    - { q: roundcube/hosts, t: string, v: localhost }
    - { q: roundcube/database-type, t: select, v: sqlite3 }
    - { q: roundcube/db/basepath, t: string, v: /var/lib/dbconfig-common/sqlite3/roundcube }
    - { q: roundcube/restart-webserver, t: boolean, v: 'false' }
  notify:
    - reconfigure roundcube
  tags:
    - webmail

- name: Install roundcube and dependencies (from backports)
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - php5-fpm
    - php5
    - php5-common
    - roundcube-sqlite3
    - roundcube-core
    - roundcube
  tags:
    - webmail

- name: Install php5-fpm configuration
  copy: src=etc/php5/fpm/{{item}} dest=/etc/php5/fpm/{{item}} owner=root group=root mode=0644
  with_items:
    - php-fpm.conf
    - php.ini
    - pool.d/www.conf
  notify:
    - restart php5-fpm
  tags:
    - webmail

- name: Set roundcube-related directories permissions
  file: path=/var/log/roundcube state=directory group=adm owner=www mode=0750 recurse=no
  tags:
    - webmail

- name: Set correct script permissions in /etc/roundcube
  file: path=/etc/roundcube/{{item}} group=www owner=root mode=0640
  with_items:
    - debian-db.php
    - main.inc.php
  tags:
    - webmail

- name: Set correct permissions for roundcube temporary directory
  file: path=/var/lib/roundcube/temp state=directory group=www owner=www mode=0750 recurse=no
  tags:
    - webmail

- name: Set correct permissions for roundcube sqlite3 directory
  file: path=/var/lib/dbconfig-common/sqlite3/roundcube group=www owner=www mode=0770 recurse=no
  tags:
    - webmail

- name: Set correct permissions for roundcube sqlite3 database file
  file: path=/var/lib/dbconfig-common/sqlite3/roundcube/roundcube state=file group=www owner=www mode=0660
  tags:
    - webmail
