- name: Install roundcube and dependencies (from backports)
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - php5-fpm
    - php5
    - php5-common
    - roundcube-sqlite3
    - roundcube-core
    - roundcube
  tags:
    - webmail

- name: Install php5-fpm configuration
  copy: src=etc/php5/fpm/{{item}} dest=/etc/php5/fpm/{{item}} owner=root group=root mode=0644
  with_items:
    - php-fpm.conf
    - php.ini
    - pool.d/www.conf
  notify:
    - restart php5-fpm
  tags:
    - webmail

- name: Configure roundcube
  debconf: name=roundcube-core question={{ item.q }} vtype={{ item.t }} value={{ item.v }}
  with_items:
    - { q: roundcube/hosts, t: string, v: localhost }
    - { q: roundcube/database-type, t: select, v: sqlite3 }
    - { q: roundcube/db/basepath, t: string, v: /var/lib/dbconfig-common/sqlite3/roundcube }
    - { q: roundcube/restart-webserver, t: boolean, v: 'false' }
  notify:
    - reconfigure roundcube
  tags:
    - webmail

- name: Set roundcube log directory permissions
  file: path=/var/log/roundcube state=directory group=adm owner=www mode=0750 recurse=no
  tags:
    - webmail
