- name: Install web server packages (from backports)
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - nginx
  tags:
    - webserver

- name: Install nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx
  tags:
    - webserver
