- name: Download Wordpress
  get_url: url=https://wordpress.org/wordpress-4.2.2.tar.gz dest=/root/wordpress-4.2.2.tar.gz sha256sum=3c4e2cc3af289366ff5352e35c3f80fca2dcaed3d56a79f33b25374c356c3f90
  tags:
    - wordpress

- name: Create wordpress group
  group: name=wordpress state=present
  tags:
    - wordpress

- name: Create wordpress user
  user: name=wordpress group=wordpress state=present shell="/bin/false" home=/var/www/wordpress createhome=no
  tags:
    - wordpress

- name: Extract Wordpress archive
  unarchive: copy=no src=/root/wordpress-4.2.2.tar.gz dest=/var/www/ creates=/var/www/wordpress owner=wordpress group=wordpress
  tags:
    - wordpress

- name: Create wordpress database
  mysql_db: login_user=root login_password={{ mysql_root_password }} name=wordpress state=present
  tags:
    - wordpress

- name: Create wordpress MySQL user and grant access to database
  mysql_user: login_user=root login_password={{ mysql_root_password }} name=wordpress state=present password={{ wordpress_mysql_password }} priv=wordpress.*:ALL
  tags:
    - wordpress

- name: Check whether wp-config.php already exists
  stat: path=/var/www/wordpress/wp-config.php
  register: wp_cfg_file
  tags:
    - wordpress

- name: Generate 64-chars wordpress keys
  command: "sed -e 's/[^[:print:]]//g; s/\\x27//g; /^.\\{512\\}$/!d; s/.\\{64\\}/&\\n/g; q' /dev/urandom"
  environment:
    LC_ALL: C
  when: (wp_cfg_file.stat.exists == False)
  register: wp_keys
  tags:
    - wordpress

- name: Install wp-config.php
  template: src=wp-config.php.j2 dest=/var/www/wordpress/wp-config.php owner=root group=wordpress mode=0640
  when: (wp_cfg_file.stat.exists == False)
  tags:
    - wordpress
