- name: Install packages for XMPP server
  apt: default_release=wheezy-backports pkg={{item}} state=installed
  with_items:
    - prosody
  tags:
    - xmpp

- name: Install Prosody main configuration file
  template: src=prosody.cfg.lua.j2 dest=/etc/prosody/prosody.cfg.lua owner=root group=prosody mode=0640
  tags:
    - xmpp
