- name: Set apt preferences
  copy:
    src: "etc/apt/preferences.d/{{ item }}"
    dest: "/etc/apt/preferences.d/{{ item }}"
    group: root
    owner: root
  with_items:
    - stable.pref
    - security.pref
    - testing.pref
  tags: letsencrypt

- name: Add Debian testing repository
  apt_repository:
    repo: "deb http://http.debian.net/debian stretch main"
    state: present
    update_cache: yes
  tags: letsencrypt

- name: Install letsencrypt client
  apt:
    pkg: letsencrypt
    state: installed
    default_release: testing
  tags: letsencrypt

- name: Generate certificates for websites
  command: "letsencrypt certonly --webroot --webroot-path /var/www/{{ item }} --email {{ webmaster_email }} -d {{ item }} --agree-tos --keep"
  with_items:
    - "{{ websites }}"
  tags: letsencrypt

- name: Configure nginx to use new certificates
  template:
    src: letsencrypt.j2
    dest: "/etc/nginx/includes/{{ item }}/letsencrypt"
    owner: root
    group: root
    mode: 0644
  with_items:
    - "{{ websites }}"
  tags: letsencrypt
  notify:
    - restart nginx

# Try to renew the certificate daily, but keep the existing certificate unless it is due to be renewed.
# Certificate renewals seem to fall due 10 days before expiry by default.
- name: Schedule certificate renewals using cron
  cron:
    name: letsencrypt renew certificate
    job: "letsencrypt certonly --webroot --webroot-path /var/www/{{ item }} --email {{ webmaster_email }} -d {{ item }} --agree-tos --keep && service nginx reload"
    cron_file: "ansible_letsencrypt_{{ item }}_cert_renewal"
    state: present
    special_time: daily
    user: root
  with_items:
    - "{{ websites }}"
  tags: letsencrypt
