- set_fact:
    current_letsencrypt_domain: "{{item.name}}"
  tags: letsencrypt

- name: Configure nginx to use LE certificate
  template:
    src: letsencrypt.j2
    dest: "/etc/nginx/includes/{{current_letsencrypt_domain}}/letsencrypt"
    owner: root
    group: root
    mode: 0644
  tags: letsencrypt
  notify:
    - restart nginx

- name: Generate certificate for current domain
  command: certbot certonly --standalone --standalone-supported-challenges http-01 --email {{ admin_email }} -d {{ current_letsencrypt_domain }} --agree-tos --keep --pre-hook "service nginx stop" --post-hook "service nginx start"
  tags: letsencrypt

