- name: Add OpenSUSE PGP signing key
  apt_key: url=http://download.opensuse.org/repositories/isv:ownCloud:community/Debian_7.0/Release.key state=present
  tags:
    - owncloud

- name: Add OpenSUSE repository for Owncloud package
  apt_repository: repo='deb http://download.opensuse.org/repositories/isv:/ownCloud:/community/Debian_7.0/ /' state=present update_cache=yes
  tags:
    - owncloud

- name: Install Owncloud and dependencies
  apt: pkg={{item}} state=installed default_release=wheezy-backports
  with_items:
    - python-configparser
    - php5-ldap
    - php-apc
    - owncloud-server
  notify:
    - restart php5-fpm
  tags:
    - owncloud

- name: Create owncloud group
  group: name=owncloud state=present
  tags:
    - owncloud

- name: Create owncloud user
  user: name=owncloud group=owncloud state=present shell="/bin/false" home=/var/www/owncloud createhome=no
  tags:
    - owncloud

- name: Set correct ownership in Owncloud directory
  file: path=/var/www/owncloud/{{item.dirname}} group=owncloud owner=owncloud recurse={{item.rec}}
  with_items:
    - { dirname: apps, rec: no }
    - { dirname: config, rec: yes }
    - { dirname: data, rec: yes }
    - { dirname: assets, rec: yes } 
  tags:
    - owncloud

- name: Set correct permissions in some Owncloud apps subdirectory
  file: path=/var/www/owncloud/apps/{{item}} group=www owner=owncloud mode="u=rwX,g=rX,o-rwx" recurse=yes
  with_items:
    - calendar
    - contacts
  tags:
    - owncloud

- name: Create owncloud database
  mysql_db: login_user=root login_password="{{mysql_root_password}}" name=owncloud state=present
  tags:
    - owncloud

- name: Create owncloud MySQL user and grant access to database
  mysql_user: login_user=root login_password="{{mysql_root_password}}" name=owncloud state=present password="{{owncloud_mysql_password}}" priv=owncloud.*:ALL
  tags:
    - owncloud

- name: Install nginx configuration part for owncloud
  template: src=nginx-owncloud.inc.j2 dest=/etc/nginx/includes/{{ server_name }}.{{ domain_name}}/owncloud owner=root group=root mode=0644
  notify:
    - restart nginx
  tags:
    - owncloud

- name: Install php-fpm configuration part for owncloud
  copy: src=etc/php5/fpm/pool.d/owncloud.conf dest=/etc/php5/fpm/pool.d/owncloud.conf owner=root group=root mode=0644
  notify:
    - restart php5-fpm
  tags:
    - owncloud

- name: Create PHP session directory for owncloud
  file: path=/var/lib/phpsession/owncloud state=directory owner=owncloud group=owncloud mode=0700 recurse=no
  tags:
    - owncloud
